version: '3.8'

services: 
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php artisan octane:start --host=0.0.0.0 --port=8000
    container_name: octane-service1
    image: laravel-image
    ports:
      - "8000:8000"
    volumes: 
      - .:/opt/www
    networks:
      - default

  horizon: 
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php artisan queue:work
    container_name: octane-horizon-service1
    image: laravel-image
    volumes: 
      - .:/opt/www
    networks:
      - default